#!/usr/bin/env ruby

require 'homebusctrlhaccess/options'
require 'homebusctrlhaccess/app'

access_app_options = HomebusCtrlhAccess::Options.new

access = HomebusCtrlhAccess::App.new access_app_options.options
access.run!
